import type { Metadata } from "next";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";

const balooBhaijaan = Baloo_Bhaijaan_2({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ["latin"],
  variable: "--font-baloo-bhaijaan",
});

export const metadata: Metadata = {
  title: "Bingo Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={balooBhaijaan.variable}>
      <body className="antialiased">
        <main>{children}</main>
      </body>
    </html>
  );
}